---
# SPDX-FileCopyrightText: 2025 The Linux Foundation
# SPDX-License-Identifier: Apache-2.0

name: 'Release Drafter'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_release_draft:
    name: 'Update Release Draft'
    permissions:
      # write permission is required to create releases
      contents: write
    runs-on: 'ubuntu-latest'
    timeout-minutes: 3
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: 'audit'

      # yamllint disable-line rule:line-length
      - uses: release-drafter/release-drafter@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e # v7.5.1
